name = "PenguinTransport"
uuid = "d3a1f7c2-9b5e-4f12-a6c3-7b9d2e1f0a4b"
version = "0.1.0"

[deps]
CartesianGeometry = "5961ddb3-e46d-41f1-806c-0197ba873d0b"
CartesianOperators = "6ffd2c7a-1a34-4f8b-a2c9-3d5e7f9b0c1d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PenguinSolverCore = "8f14e45f-7d0b-4a6b-9c1e-2f3d4b5a6c7d"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CartesianGeometry = "0.1"
CartesianOperators = "0.1"
OrdinaryDiffEq = "6.108.0"
PenguinSolverCore = "0.1"
SciMLBase = "2.144.2"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
